# fly.toml app configuration file generated for bulls-ai-web-server on 2023-10-03T11:16:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bulls-ai-web-server"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
